### ISSUE TITLE
ECU-C DS3-L no inverter signal, voltage unavailable after reboot, model unknown

### ISSUE THREAD

**Issue by gratjetost** [tv3/homeassistant-apsystems_ecur#6]
@tv3 I took your fork for the APS after the discussion in the "official" github from ksheumaker.
At the moment the basics work. But I encounter some issues with the DS3-L (703) inverters.
To start: the model in HACS is unknown.  

After a reboot I always get an error that the Voltage cannot be read:

`Logger: homeassistant.components.sensor
Source: custom_components/apsystems_ecur/sensor.py:131
Integration: Sensor (documentation, issues)
First occurred: 10:51:55 (2 occurrences)
Last logged: 10:51:55

Error adding entities for domain sensor with platform apsystems_ecur
Error while setting up apsystems_ecur platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 810, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/apsystems_ecur/sensor.py", line 131, in state
    return self.coordinator.data.get("inverters", {}).get(self._uid, {}).get("voltage", [])[0]
IndexError: list index out of range
`

Also the signal strength is always 0 % (not an big issue, but worth to mention).
Refreshing the whole inverter sensors are unstable. Sometimes it refreshes not at all. Sometimes a couple of times a day. But never every 5 minutes.

the ECU-C part works still good after a few days without rebooting the ECU-C.

some pictures:

![2022-06-10 11_01_17-Settings – Home Assistant — Mozilla Firefox](https://user-images.githubusercontent.com/11716629/173031236-79cc8649-d6b8-4b17-82b4-fcfa3d95e56a.png)
![2022-06-10 11_01_52-History – Home Assistant — Mozilla Firefox](https://user-images.githubusercontent.com/11716629/173031239-87015af7-2937-4af6-a25c-f6e292c6b08e.png)
![2022-06-10 11_01_33-Settings – Home Assistant — Mozilla Firefox](https://user-images.githubusercontent.com/11716629/173031241-033ab10b-d377-4047-847b-56a9f63bf017.png)

**Comment by dewi-ny-je** [comment]
I have similar issues with ECU-r pro, latest commit.
